### ISSUE TITLE
Crash in Critter Traits

### ISSUE THREAD

**Issue by Pierre-St** [heinermann/ONI_Mods#3]
Hi,
I just encountered a crash in ONI with Critter traits enabled. Log file attached.

Pierre

[output_log_crash.txt](https://github.com/heinermann/ONI_Mods/files/4411454/output_log_crash.txt)

**Comment by heinermann** [comment]
Hello, sorry I've removed Critter Traits from the Steam Workshop because people kept encountering crashes which I've been unable to reproduce.

If you can find another owner who is interested in fixing and maintaining CritterTraits then I'd be happy to hand it over to them.
